crosswalk-project/chromium-crosswalk

ui/ozone/common/native_display_delegate_ozone.h
This class is used by ozone-wayland, but building Crosswalk with
`-Dcomponent=shared_library` causes linking to fail because this symbol is
not exported by libozone.so even though it is referenced in
libwayland.so.
The best approach upstream is still being discussed, including using a
different class in ozone-wayland. For now, we need it for XWALK-2571, as
building Crosswalk in shared library mode is part of the solution for
it.
=> [Temp] Export ui::NativeDisplayDelegateOzone.

net/socket/unix_domain_client_socket_posix.cc
Rather than return ERR_NOT_IMPLEMENTED it seems sensible to
return ERR_SOCKET_NOT_CONNECTED in the case that the socket
is not connected, but unconditionally return ERR_ADDRESS_INVALID
if connected (because there's no IP addr or port associated
with either end of the socket).
BUG=431412
Review URL: https://codereview.chromium.org/841993002
Cr-Commit-Position: refs/heads/master@{#310564}
=> [Temp] Make unix socket Get{Peer|Local}Address return more rational errors.

base/BUILD.gn, base/base.gyp, base/base.gypi, build/common.gypi
Use glib main loop when building Ozone (not only for the
extension process). This will make glib based external
extensions work when disabling the extension process.
TODO: squash this patch with the two others of the same kind.
=> [Extensions] Build glib message pump on Ozone by default

content/browser/frame_host/navigation_controller_impl.cc, content/browser/frame_host/navigation_controller_impl_unittest.cc
BUG=449075
TEST=content_unittests --gtest_filter=NavigationControllerTest.IsInPageNavigation
Review URL: https://codereview.chromium.org/855883002
Cr-Commit-Position: refs/heads/master@{#313051}
(cherry picked from commit 3d426436e10135a99f5e54fe1135767eb55712db)
=> Allow universal access from file if flag is set and url is file scheme.

build/android/pylib/android_commands.py, build/android/pylib/device/device_utils.py, build/android/pylib/device/device_utils_test.py
There have been some changes in M41 that causes our device tests to fail on the ICS devices we have. This pull request backports some fixes I made upstream for them so that we get back to a usable state.
We still upload some binaries (like `device_forwarder`) to the device more often than we actually need (see [this Chromium bug I reported](https://code.google.com/p/chromium/issues/detail?id=458658) for more information), but it is nothing too huge.
=> [Android] Backport some upstream commits to fix our device tests.

content/child/runtime_features.cc
This CL reverts
https://codereview.chromium.org/669673003 Use the "enableCSSViewport" method to enable CSS viewport feature
and
https://codereview.chromium.org/633943002 Fix the "--enable-viewport" command line option
BUG=432813
Review URL: https://codereview.chromium.org/791123003
Cr-Commit-Position: refs/heads/master@{#307815}
(cherry picked from commit 602289d4c714b77a44fd8694915b05650259012d)
BUG=XWALK-3574
=> Revert @viewport enabling patches

content/child/runtime_features.cc
We support notifications in Android but upstream doesn't so we
should make sure they are enabled.
We should really consider if the "desktop" notifications are the way
forward for us in Android now that we have ServiceWorker and
push notifications.
https://codereview.chromium.org/920153002
BUG=XWALK-3653
=> [Android] Allow constructor of Notifications on Android.

content/public/android/java/src/org/chromium/content/browser/ContentViewRenderView.java
Use this API to control whether the SurfaceView's surface is placed on top of its window.
Note this only works when SurfaceView is used. For TextureView, it doesn't work.
Related to XWALK-3778,XWALK-3742
=> [Android] Implement ContentViewRenderView.setZOrderOnTop

content/browser/android/content_startup_flags.cc
Upstream recently enabled support for notifications and Push API on
Android >= Jelly Bean (see commit d948e026, "Exceptions for enabling Web
Notifications and the Push API by default").
Our support for notifications in Crosswalk is currently simpler (more
similar to desktop-style notifications) and works on ICS devices as
well, so we can be more lax about which devices we actually support.
Related to: XWALK-3654
=> [Android] Enable support for notifications on ICS devices.

content/browser/zygote_host/zygote_host_impl_linux.cc, content/public/common/content_switches.cc, content/public/common/content_switches.h, media/base/media_posix.cc
Due to licensing issues, the pre-built binary doesn't ship with the
necessary codecs for patented media formats. Therefore, mp4/mp3 files
can't be played back by Crosswalk.
Add a command line option so that mp4/mp3 files can be played by loading
the proprietary library. An example is,
xwalk --proprietary-codec-lib-path=/opt/google/chrome/libffmpegsumo.so
=> Add the command line option to load proprietary codec library.

build/common.gypi
The code in blink project will use the flag disable_webaudio_hrtf to reduce the binary size.
This patch is backported from the crosswalk-lite branch.
=> Add flag to diable hrtf in webaudio

build/common.gypi, content/child/blink_platform_impl.cc, ui/resources/ui_resources.grd
Remove following resources:
1. Resources for media player control bar, this part is not usually
used, thus it could be overriden by web developers.
2. The ui resources are for aura/views, Android doesn't need it.
This patch is the backport from Crosswalk-lite
BUG=https://crosswalk-project.org/jira/browse/XWALK-3928
TEST=Build with/without flag use_minimum_resources and simple test on XWalkCoreShell.apk
SIZE_REDUCED=212k(Release build on ARM)
=> Add gyp flag use_minimum_resources and exclude unnecessary resources

android_webview/lib/main/aw_main_delegate.cc, content/browser/browser_main_loop.cc, content/browser/dom_storage/dom_storage_area.cc, content/browser/dom_storage/dom_storage_area.h, content/public/common/content_switches.cc, content/public/common/content_switches.h
Android WebView does not save data during shutdown like Chrome does.
Adding an --enable-aggressive-domstorage-flushing flag to return the
DOM Storage implementation to the prior implementation which had a 1
sec. timer to flush the commit queue.
NOTRY=true
NOPRESUBMIT=true
TBR=jsbell
BUG=479767
Review URL: https://codereview.chromium.org/1129233003
Cr-Commit-Position: refs/heads/master@{#329070}
(cherry picked from commit a1f8d834ce9fc89e5e409e08bb00173c37854329)
Review URL: https://codereview.chromium.org/1138843002
Cr-Commit-Position: refs/branch-heads/2357@{#364}
Cr-Branched-From: 59d4494849b405682265ed5d3f5164573b9a939b-refs/heads/master@{#323860}
(cherry picked from commit 5eba2222bb5e2f70618d3fa3017d19a91504e823)
=> localStorage: Aggressively flush to disk for Android WebView.

base/icu_alternatives_on_android/icu_utils.cc, base/icu_alternatives_on_android/java/src/org/chromium/base/icu/IcuUtils.java
The line break property for ICU can't be supported without extra libs like ICU4j.
BUG=XWALK-4645
=> [Lite][Android] Crash found when executes "selection.addRange", caused by icu feature.

build/common.gypi
Leverage the existent build flag 'enable_webrtc' to achieve this.
With "-Ddisable_webrtc=1", the size of "libxwalkcore.so" is reduced by 4M.
=> To disable WebRTC solely.

content/browser/media/android/browser_media_player_manager.cc, content/browser/media/android/browser_media_player_manager.h, content/browser/media/media_web_contents_observer.cc, content/browser/renderer_host/render_process_host_impl.cc, content/browser/renderer_host/render_view_host_impl.cc, content/browser/web_contents/web_contents_impl.cc, content/content_browser.gypi
Build with "-Ddisable_web_audio" will reduce size by 0.3M.
Details of patch:
(1) The macro 'DISABLE_WEB_AUDIO' will disable the WebAudio related
code in 'content' folder.
(2) Set the building flag 'use_openmax_dl_fft' to 0 will disable the
WebAudio related code for Android in blink eventrually, leveraging
the macro 'ENABLE_WEB_AUDIO'.
=> To disable WebAudio solely.

base/android/java/src/org/chromium/base/ResourceExtractor.java
The upstream changes from M45 almost make our following commits unnecessary. This patch is to resolve the conflicts and restore previous functionality.
This patch rebased the commits below:
4ba805f1c8d470eb7c32348f2d3c8df28199f7ce
c715ce1b87516f983620c32919a0f99db095bcbe
The commit below can be discared:
31d05593d00b70050a9b4fc6d14f33a5b56fc60e
After this patch get merged, I will send another PR to Crosswalk repository. Then XWALK-4755 can be fixed.
=> Fix the conflicts of ResourceExtractor on M45

content/browser/media/android/browser_media_player_manager.cc, content/browser/media/android/browser_media_player_manager.h, content/browser/media/media_web_contents_observer.cc, content/browser/renderer_host/render_process_host_impl.cc, content/browser/renderer_host/render_view_host_impl.cc, content/browser/web_contents/web_contents_impl.cc, content/content_browser.gypi
Bring back MediaPlayersOberver and AudioRenderHost.
Remove MediaPlayersObserver will cause the Chrome_IO thread crash,
whereas remove AudioRenderHost will cause main thread crash.
BUG=XWALK-4965
=> Web Audio bug fix

build/android/increase_size_for_speed.gypi
Modules like Base,Skia,cc,V8 use "increase size for speed" to
run faster.In Lite we prefer to decrease size.
With lzma, 677K binary size reduced for embedded_shell.apk
Without lzma, 820K binary size reduced.
Slight performance downgrade found,it is an acceptable balance.
=> Add 'Optimize for size, Os' compile option

content/child/blink_platform_impl.cc
This reverts commit ef3e7c6eadb30fccdd7c0881119d659a5aedad86.
For crosswalk-lite-10, a macro named IDR_UASTYLE_HTML_CSS generate in
./gen/blink/public/resources/grit/blink_resources.h,
whether the option use_minimum_resources is enable or disable.
In crosswalk-lite, IDR_UASTYLE_HTML_CSS would not generate if we disable
use_minimum_resources, so we need add it back to avoid the compiling
error.
Simply remove IDR_UASTYLE_HTML_CSS html.css will cause the layout mess
up.
=> Revert "Bug fix for minimum resources"

build/common.gypi
-fstack-protector is used for preventing buffer overflow attack.
But it also brings larger binary size. it is also controlled by
flag: "use_optimize_for_size_compile_option".
With lzma, ~200K binary size reduced for EmbeddedShell.apk.
=> [Lite] Remove "-fstack-protector" compile option

content/child/blink_platform_impl.cc
It causes the problem of lost 'Play' button in Video Element.
=> Web-Video-related resources should be controled by 'disable_web_video'

content/child/runtime_features.cc
I've awared of this problem during investigation of XWALK-5147. It caused by user trying to access a webpage with complicated 'video' tag related content when WebVideo is disabled.
Although the calling of system Media Player is excluded when disable
WebVideo, if the WebKit still takes <video> as a known tag, there will
be risk of many unexpected problems.
=> Make the HTML tag "video" unknown for WebKit if WebVideo disabled

ui/android/java/src/org/chromium/ui/VSyncMonitor.java
The change of VSyncMonitor in the commit af926cfcaed81686e6dbf782932b22deed1bef4c
causes crash of XWalkCoreShell and XWalkCoreInternallShell,
and then blocks a lot of test cases.
This commit is to fix the crash.
Related bug: XWALK-5241
=> [Android] Fix crash in unit test

content/content.gyp, content/public/android/java/src/org/chromium/content/browser/accessibility/AccessibilityInjector.java
As part of the efforts to stop depending on external packages in the
code, replace usage of org.apache.http classes with an implementation
that only uses apache.net.Uri.
This allows us to drop the dependency on the legacy_http_client target
and end up having to bundle org.apache.http.legacy.jar into
xwalk_core_library.jar.
Not upstreamable, as the code in question was removed upstream when they
dropped support for ICS.
Related to: XWALK-5092
=> [Android] Stop using org.apache.http classes in AccessibilityInjector.

content/renderer/render_view_impl.cc, content/renderer/render_view_impl.h
Leverage the existent flag "enable_plugins" to exclude related code of
Chromium.
Flag = disable_plugins
Reduced size = 440K
=> [Lite] To disable Plugin

content/content.gyp, content/public/android/java/src/org/chromium/content/browser/accessibility/AccessibilityInjector.java
As part of the efforts to stop depending on external packages in the
code, replace usage of org.apache.http classes with an implementation
that only uses apache.net.Uri.
This allows us to drop the dependency on the legacy_http_client target
and end up having to bundle org.apache.http.legacy.jar into
xwalk_core_library.jar.
Not upstreamable, as the code in question was removed upstream when they
dropped support for ICS.
Related to: XWALK-5092
(cherry picked from commit 5909ede1bf2c0d7e05b2ea1cd9542fba4ae8e0dd)
=> crosswalk-16: [Android] Stop using org.apache.http classes in AccessibilityInjector.

content/content_renderer.gypi, content/renderer/render_thread_impl.cc, content/renderer/render_thread_impl.h
Flag = disable_mediastream
Reduced size = 30K
=> [Lite] To disable Mediastream

content/child/runtime_features.cc
The demo at https://storage.googleapis.com/presentation-api/index.html
can be used to see how the API is works.
The Crosswalk Presentation API implementation on Windows requires
having a connected non-primary display (either wired (HDMI, Display Port, ...)
or wireless (miracast)).
BUG=XWALK-4811
=> [Windows]Enable presentation API

base/process/launch_win.cc
Backported so that we can launch our Windows bots from the Windows Task
Scheduler. Original commit message:
> This bit of code was added in 2010 by commit 66ae36fec ("Restricting
> lifetime of python sync server on Windows via a JobObject"). The
> rationale at the time was that running a test case under a debugger
> would associate all new processes with the debugger's job object.
>
> Since 2010, Windows 8 and others have been releases, all of which
> support nested jobs and do not require processes to be created with
> the CREATE_BREAKAWAY_FROM_JOB. Not only that, but unconditionally
> setting that flag prevents browser tests from the Windows Task
> Scheduler at least on Windows 8 and later: the Task Scheduler creates
> a job object to launch the test(s), and calling CreateProcess() with …
=> [Backport] Conditionally set CREATE_BREAKAWAY_FROM_JOB when job objects are used.

.gitignore, media/base/media_switches.cc, media/base/media_switches.h, media/capture/video/video_capture_device.cc, media/capture/video/video_capture_device.h, media/capture/video/win/video_capture_device_factory_win.cc, media/capture/video/win/video_capture_device_factory_win.h, media/capture/video/win/video_capture_device_rs_win.cc, media/capture/video/win/video_capture_device_rs_win.h, media/capture/video/win/video_capture_device_rs_win_null.cc, media/capture/video/win/video_capture_device_rs_win_null.h, media/media.gyp
Add Intel RSSDK based video capture device VideoCaptureDeviceRSWin.
It allows:
1. Crosswalk apps are able to share the RealSense camera with other
native apps simultaneously.
2. Crosswalk apps are able to use getUserMedia API to preview RealSense
camera in real-time while accessing RSSDK middlewares in Crosswalk
extensions simultaneously.
This feature is behind --use-rs-video-capture flag.
TEST=
On a device with RealSense camera and RSSDK, execute
1. DF_RawStreams.exe (RSSDK sample)
2. xwalk.exe --use-rs-video-capture
https://webrtc.github.io/samples/src/content/devices/input-output/
Crosswalk and DF_RawStreams.exe should capture video frame from
RealSense camera simultaneously.
BUG=XWALK-6028
=> [Windows] Support RealSense Cameras

content/public/android/java/src/org/chromium/content/browser/ContentView.java
Unlike WebView, XWalkView uses a ContentView object as its child view,
which is actually receiving all kinds of events such as touching and
clicking. To let the XWalkView object receive these events too, it's
necessary to override relevant methods of ContentView and redirect
them to the XWalkView object. So we add XWalkContentView and have it
extend ContentView. To make this possible, the contructor of ContentView
must be public.
XWalkContentView is a temporary solution. We are targeting to optimize
the hierarchy of XWalkView to make it more like WebView. This task can
be tracked via XWALK-6118.
BUG=XWALK-6014
=> [Android] Expose the constructor of ContentView

base/icu_alternatives_on_android/icu_utils.cc
[Android][ICU] Fix error always true of icu_utils
icu_utils.[cc|h] is the ICU JNI alternative C++ bridge, it will be enabled
by build flag "use_icu_alternatives_on_android=1". The in/out parameter *error
of functions toLower(), toUpper() and normalize() are be set true at any time.
The caller will detect that error and then drop the result.
The fix simply to set the error as false. Even the conversion failed, the
original string will be returned, which is no harm.
BUG=XWALK-6161
=> [Android][ICU] Fix error always true of icu_utils

third_party/WebKit/Source/build/features.gypi
This change (together with a follow-up in the Crosswalk repository
itself) moves the definition of the ENABLE_WEBCL macro to Blink's
features.gypi, so that it is only passed to the relevant modules and
bindings files intead of all the 15000+ files part of Crosswalk's build.
This part of the fix only adds the definition to the Blink side; the
Crosswalk patch will stop defining the macro for the other files.
=> [Blink] WebCL: Only set ENABLE_WEBCL in the relevant files.

chrome/installer/mini_installer/chrome.release, chrome/tools/build/win/FILES.cfg, content/browser/gamepad/gamepad_platform_data_fetcher_win.cc, content/browser/gamepad/gamepad_platform_data_fetcher_win.h, content/content_common.gypi, tools/checkbins/checkbins.py
XWALK-4992 [windows] App does not support gamepad
While chromium is bundling xinput1_3.dll from DirectX redist, using whatever
platform suports. Logic about what dll is in use for different platforms is
copied from Xinput.h.
In order to target all of the Windows versions with the same binary, chosen to
keep dynamic linking approach. Otherwise, there would be a problem with
XInputEnable not available in xinput dll before Windows8 and deprecated on
Windows 10.
Snippet from <ProgramFiles>\Windows Kits\10\Include\10.0.10586.0\um\Xinput.h:
#if(_WIN32_WINNT >= _WIN32_WINNT_WIN8)
#define XINPUT_DLL_A  "xinput1_4.dll"
#define XINPUT_DLL_W L"xinput1_4.dll"
#else
#define XINPUT_DLL_A  "xinput9_1_0.dll"
#define XINPUT_DLL_W L"xinput9_1_0.dll"
#endif
For detailed information on Windows library …
=> XWALK-4992 [windows] App does not support gamepad

third_party/WebKit/Source/wtf/text/TextCodecICUAlternatives.cpp, third_party/WebKit/Source/wtf/text/TextCodecICUAlternatives.h, third_party/WebKit/Source/wtf/text/TextEncodingRegistry.cpp, third_party/WebKit/Source/wtf/wtf.gyp
The "use_icu_alternatives_on_android=1" flag cut off the icu c++
library, which breaks the Shift-JIS encode and decode functions.
So we add a TextCodecICUAlternatives class which provides such
functions by using the Java class CharsetEncoder and
CharsetDecoder.
BUG=XWALK-6175
=> [Android][ICU] Add Shift-JIS codec support.

content/browser/web_contents/web_contents_impl.cc, content/browser/web_contents/web_contents_impl.h, content/public/browser/web_contents.h
This reverts commit dddd14d2ca1040128d41dff9c5391efd0a267633.
This change was only used by the Tizen port, which got removed last
year.
=> Revert "Provide a ScreenOrientationDispatcherHost getter."

ui/views/controls/native/native_view_host.cc, ui/views/controls/native/native_view_host.h, ui/views/view.cc, ui/views/view.h, ui/views/widget/desktop_aura/desktop_window_tree_host_win.cc, ui/views/widget/desktop_aura/desktop_window_tree_host_win.h, ui/views/widget/native_widget_delegate.h, ui/views/widget/widget.cc, ui/views/widget/widget.h, ui/views/win/hwnd_message_handler.cc, ui/views/win/hwnd_message_handler_delegate.h
BUG=XWALK-5503
Some OSs (e.g. Windows and Linux) don't mark windows as hidden on screen
lock or when other opaque windows fully cover them.
Note that e.g. OSX and Android do this while Windows and Linux don't.
OnSoftVisibilityChanged enables that OS window state is kept as is (on
Linux and Windows) and that e.g. power saving PageVisibility API is still
properly triggered.
The first patch here targets Windows and screen lock.
=> Page Visibility API: visibilitychange on Windows screen lock/unlock

content/browser/browser_main_loop.cc, content/browser/browser_main_loop.h, content/browser/screen_orientation/screen_orientation_delegate_win.cc, content/browser/screen_orientation/screen_orientation_delegate_win.h, content/child/runtime_features.cc, content/content_browser.gypi
BUG=XWALK-5002
[windows] App does not support orientation lock
This patch implements Screen orientation lock API for Windows.
Note: On Windows 8 and later, fullscreen is not mandatory to get application
prefered locking - so API works regardless if it is in fullscreen mode or not.
=> Screen orientation lock implementation for Windows

build/java_apk.gypi
Apk is actually a common zip file. Since Lite-17, the default
behavior of generating apk has been changed as not compressing
.dat .pak and .bin files. So,the final apk size is much bigger.
Take Lite for example, xwalk.pak file is ~800K, if we compress
it when generating apk, the final apk size is 500K smaller.
=> [Lite] Set aapt to do compressing on all the apk contents.

content/browser/android/content_view_core_impl.cc, content/public/android/java/src/org/chromium/content/browser/ContentViewCore.java
If set the WindowBackground of Activity to RED, and webpage page's backgroudn to RED,
when application starts or resumes after click back key, it will showup a white screen
shortly. With this SetBackgroundColor, we can change the first screen to a specified color,
which can help to avoid white screen.
Related BUG=XWALK-4809, XWALK-4995
=> [Android] Add SetBackgroundColor to avoid white screen on startup

media/base/android/java/src/org/chromium/media/MediaCodecUtil.java, media/base/android/java/src/org/chromium/media/MediaPlayerBridge.java
Adapt to:
https://codereview.chromium.org/1506013009
https://codereview.chromium.org/1588503004
Some interfaces for media were added from API level 16, we need to check
it at runtime otherwise app will be crashed when it runs on ICS.
Add the checks for API level, if API level is less than JELLY_BEAN,
return default value.
BUG=XWALK-6494
=> [Android] Fix the lint warnings for Media classes.

.gitignore, third_party/khronos/CL/cl.h, third_party/khronos/CL/cl.hpp, third_party/khronos/CL/cl_d3d10.h, third_party/khronos/CL/cl_d3d11.h, third_party/khronos/CL/cl_dx9_media_sharing.h, third_party/khronos/CL/cl_egl.h, third_party/khronos/CL/cl_ext.h, third_party/khronos/CL/cl_gl.h, third_party/khronos/CL/cl_gl_ext.h, third_party/khronos/CL/cl_platform.h, third_party/khronos/CL/opencl.h
With M49, the WebCL code is always being built, so we need the OpenCL
headers here for pure chromium-crosswalk content_shell builds to work,
since they do not check out Crosswalk and pull its dependencies.
BUG=XWALK-6661
=> WebCL: Import OpenCL headers into chromium-crosswalk.

third_party/WebKit/Source/core/css/CSSRule.h
Subclass was exported but not the base class. It triggers a warning
which stops the build.
Fixed upstream by CL https://codereview.chromium.org/1637273003
=> [Windows] Fix build.

PRESUBMIT.py
This commit allows us to turn on the file permission checks in Crosswalk's
`PRESUBMIT.py`.
Original commit message:
------------------------
Like _GetIDLParseError(), use input_api.PresubmitLocalPath() to
determine checkperms.py's full path instead of just using
"tools/checkperms/checkperms.py".
While the latter works just fine for Chromium, using an absolute path
helps downstreams that may use Chromium's PRESUBMIT checks in their own
files.
R=jochen@chromium.org,phajdan.jr@chromium.org
Review URL: https://codereview.chromium.org/1847373003
=> [Backport] PRESUBMIT: Determine checkperms.py's path using input_api.

third_party/WebKit/Source/bindings/modules/v8/custom/custom.gni
This commit enables GN build of the WebCL module. Files for custom
bindings are the only ones that need to be added to GN
configuration. All other files of the WebCL module are imported from GYP
configurations automatically. The patch has been tested with a vanilla
Chromium + WebCL build.
=> [WebCL] Enable GN build.

third_party/WebKit/Source/core/inspector/InspectorHeapProfilerAgent.cpp, third_party/WebKit/Source/core/inspector/InspectorHeapProfilerAgent.h, third_party/WebKit/Source/devtools/front_end/sdk/HeapProfilerModel.js, third_party/WebKit/Source/devtools/protocol.json, third_party/WebKit/Source/platform/v8_inspector/V8HeapProfilerAgentImpl.cpp, third_party/WebKit/Source/platform/v8_inspector/V8HeapProfilerAgentImpl.h, third_party/WebKit/Source/platform/v8_inspector/V8ProfilerAgentImpl.cpp, third_party/WebKit/Source/platform/v8_inspector/public/V8HeapProfilerAgent.h
This patch includes in-depth allocation tracker and extention of
protocol.json by stackEntryLine that is used for total time annotations in
CPU profiling.
Details of HeapProfiler: Three new commands were added by analogy with
Chrome DevTools allocation tracker. Start/Stop and Event which is sent by timer.
Command stopTrackingHeapXDK accepts three parameters: stack depth for unwinding,
Sample After Value - period of timer and a flag to collect retention
information or not. Event sends to the host currently collected data about
symbols/callstack/objects. Command stopTrackingHeapXDK returns the final
info witch is similar to Event passed format with one more parameter:
duration of the collection.
Basing on this info consumer can build allocation call tree for any period
of time, annotate …
=> [XDK] Add in-depth allocation tracker

ui/resources/ui_resources.grd
GYP complains when setting use_minimum_resource=0. Two resources are
duplicate defined: IDR_MENU_CHECK_CHECKED and IDR_MENU_DROPARROW.
That's because they have already been defined no matter use_minimum_resource
is switched on/off.
The definition inside the condition block for use_minimum_resource is removed. 
@PeterWangIntel @heke123 @halton
=> [Lite] remove duplicate defined resources

net/quic/quic_protocol.h
Orignal commit message:
> Disable static_assert about TransmissionInfo size to pass debug build.
>
> R=rch@chromium.org
> BUG=590140
>
> Committed: https://crrev.com/0e72481a295461c7ff302503a984c1771e597b1e
> Cr-Commit-Position: refs/heads/master@{#388269}
>
> patch from issue 1902793002 at patchset 1 (http://crrev.com/1902793002#ps1)
=> [Backport] Disable static_assert about TransmissionInfo size to pass debug build.

third_party/WebKit/Source/platform/blink_platform.gyp
FontRendererStyle was excluded.
Fixing https://codereview.chromium.org/1944993003/ issue that missed
FontRendererStyle.cpp in gyp file
=> M52: Fix blink_platform.gyp for Android build.

base/BUILD.gn, build/config/features.gni, content/public/android/BUILD.gn
This pull request contains a few separate patches, all of which are required in order to be able to build the `content_shell_apk` target using GN with Crosswalk's local modifications on top of the upstream commits.
* "[Temp] Make |enable_webvr==false| work in GN" and "[Android] Add ApplicationStatusManager.java to the GN build" just add some new or moved files to the respective `BUILD.gn` files. Their commit messages indicate which commits they should be squashed into in the future.
* "[Backport] GN: Set |enable_webvr| in the declare_args() block" is a backport from a commit I landed upstream that makes it possible to override the value of `enable_webvr` (which we currently need to disable in Crosswalk).
Linux and Windows are out of the scope of this pull request: they will be handled …
=> [Android] Make it possible to build content_shell_apk with GN.

media/blink/cdm_session_adapter.cc, third_party/WebKit/Source/modules/encryptedmedia/ContentDecryptionModuleResultPromise.cpp, third_party/WebKit/Source/modules/encryptedmedia/ContentDecryptionModuleResultPromise.h
Outstanding promises may get rejected due to blink garbage collection
destroying all the remaining EME objects when they are no longer
referenced. The original fix destroyed the CDM asynchronously.
However, that causes problems as the CDM may hold references to
objects owned by RenderFrameImpl, and they may get accessed after
~RenderFrameImpl.
This fix posts a task to reject the promise asynchronously. That way
any outstanding promises that need to be rejected are handled after
gc is done. It affects all EME promise rejections (from Chromium).
Resolving promises is still done synchronously as there may be events
already posted that need to happen only after the promise is resolved.
BUG=597355
TEST=existing EME tests still pass
Review-Url: https://codereview.chromium.org/1987883002 …
=> [Backport] Change back to destroy the CDM synchronously

.gn
As Chromium will deprecate GYP build system since M54, we need to enable
GN build support for Crosswalk as soon as possible.
Set xwalk as "extra_deps" to Chromium in xwalk/build/common.gni:
`root_extra_deps = [ "//xwalk:xwalk_builder" ]`
=> Add GN build support for crosswalk-linux

build_overrides/v8.gni
This is necessary for us to be able to change the value of
v8_use_external_startup_data in Crosswalk.
**IMPORTANT**: In M52 we only get rid of v8_use_external_startup_data, as
https://codereview.chromium.org/2024833002/ does not apply cleanly on
M52's V8. This patch must be rewritten for M53 to contain the entire
upstream change.
See also: crosswalk-project/v8-crosswalk#164
Original commit message:
> Remove chromium defaults for v8_optimized_debug and
> v8_use_external_startup_data.
>
> This is not needed after v8 provides these defaults:
> https://codereview.chromium.org/2025803003/
> https://codereview.chromium.org/2024833002/
>
> It also interferes if somebody tries to override the gn args
> with a different value.
>
> BUG=chromium:616034
> TBR=alokp@chromium.org, brettw@chromium.org
> …
=> [Backport] gn: Remove unnecessary v8 defaults

build_overrides/v8.gni
This is the Chromium side of crosswalk-project/v8-crosswalk#166.
Kind of revert 0908bc7 ("[Backport] gn: Remove unnecessary v8 defaults")
in the sense that `v8_use_external_startup_data` is being declared in
build_overrides/v8.gni again, but it is now enclosed in a `declare_args`
block.
We cannot just get rid of it as intended in 0908bc7, as M52's V8 does
not contain `gni/v8.gni` and a lot of declarations are done in V8's
top-level `BUILD.gn` instead.
Once we move to M53, V8 will work as intended and we will only need to
properly backport https://codereview.chromium.org/2058033002 to
chromium-crosswalk.
=> [Temp] Declare v8_use_external_startup_data in build_overrides/v8.gni

content/renderer/media/renderer_webaudiodevice_impl.h
../../content/renderer/media/renderer_webaudiodevice_impl.h:94:25: error: private field 'device_position_' is not used
media::StreamPosition device_position_;
^
=> Remove unused private field device_position_

content/public/android/BUILD.gn, device/BUILD.gn
This patch set first reverts "[Temp] Make |enable_webvr==false| work in GN" (see my comment in accdb96d922d789bf8204ff4ca1af87d09673c90) and later implements the same thing in the right files.
You can get rid of both the first commit and accdb96d922d789bf8204ff4ca1af87d09673c90, as only "[Temp] Only depend on deviecs/vr when enable_webvr is on" is required in M53.
=> next: Rebase patch controlling the WebVR build

build/config/android/internal_rules.gni
Required in order to land the Crosswalk Android GN port. This is already
part of M53.
Original commit message:
> Currently, the deps of the internal targets are setup inccorrectly:
>     ERROR Input to target not generated by a dependency.
>
> BUG=none
>
> Review-Url: https://codereview.chromium.org/2001573003
=> [Backport] GN: Fix java_library() when supplied with a generated .java

build/config/BUILDCONFIG.gn, build/config/win/BUILD.gn
This patch is required for the .NET extension bridge to be built.
RELATED BUG=XWALK-7336
> Create separate configurations for passing "/MD", "/MT" and their debug
> variants: "dynamic_crt" passes "/MD" and "/MDd", whereas "static_crt"
> passes "/MT" and "/MTd". BUILDCONFIG then depends on "default_crt",
> which has some logic to choose whether to use either dynamic_crt or
> static_crt.
>
> The main reason behind this is to allow users to config -= the
> "default_crt" config: in gyp, it was possible to configure what was
> going to be passed to the compiler via the
> "win_{release,debug}_RuntimeLibrary" variable, which was useful when
> building code that needs to pass "/CLR", as it requires "/MD" and does
> not work with "/MT".
>
> …
=> [Backport][Windows] Pass "/MD" and variants outside the "runtime_library" target

media/capture/BUILD.gn
This commit should be squashed into "[Windows] Support RealSense
Cameras" in the future. It simply does the same thing in GN: a new
argument `use_rssdk` has been added (defaulting to `false`) and takes
care of selecting which RSSDK files to include.
This is an improved version of a patch originally written by Ke He
<ke.he@intel.com>.
=> [Windows] GN: Add missing RSSDK files in media/.

content/renderer/media/renderer_webaudiodevice_impl.h
Remove a stray line that should have been removed in e762df3 ("Revert
AudioDestinationNode.devicePosition commits"). It was preventing the
build from succeeding.
RELATED BUG=XWALK-7030
RELATED BUG=XWALK-7226
=> crosswalk-22: Fix the build after e762df3

content/browser/renderer_host/render_message_filter.cc, content/browser/renderer_host/render_message_filter.h, content/common/view_messages.h, content/content_renderer.gypi, content/renderer/BUILD.gn, content/renderer/media/android/audio_decoder_android.cc, content/renderer/media/android/audio_decoder_android.h, content/renderer/renderer_blink_platform_impl.cc, media/base/android/BUILD.gn, media/base/android/java/src/org/chromium/media/WebAudioMediaCodecBridge.java, media/base/android/media_jni_registrar.cc, media/base/android/webaudio_media_codec_bridge.cc, media/base/android/webaudio_media_codec_bridge.h, media/base/android/webaudio_media_codec_info.h, media/media.gyp
This reverts the following commit:
* c0baf4af ("Replace WebAudio MediaCodec usage with FFmpeg. A ~4x improvement.")
This code was reverted because Crosswalk disable the unified media pipeline
in the commit 18c4d465 of xwalk.
BUG=XWALK-7307
=> Revert "Replace WebAudio MediaCodec usage with FFmpeg" commit
